/* 
© 2025 Aravinth Raj R. All rights reserved.
Unauthorized copying of this file, via any medium, is strictly prohibited.
Proprietary and confidential.  
Written by Aravinth Raj R <aravinthr235@gmail.com>, 2025.
*/
import { mergeTypeDefs } from '@graphql-tools/merge';

// TypeDefs
import {
  enumTypeDef,
  modelTypeDef,
  getRolesTypeDef,
  getAllUsersTypeDef,
  getUserTypeDef,
  updateUserTypeDef,
  getAccessTokenTypeDef,
  addCategoryTypeDef,
  getAllCategoriesTypeDef,
  addProductTypeDef,
  updateProductTypeDef,
  getAllProductsTypeDef,
  deleteProductTypeDef,
  createOrderTypeDefs,
  paymentTypeDef,
  cancelOrderTypeDef,
  updateOrderTypeDef,
  getAllOrdersTypeDef,
  getOrderTypeDef,
  getSalesTypeDef,
  getSalesReportTypeDef,
  getTransactionsTypeDef,
  getTransactionsReportTypeDef,
  getIncomingStockTypeDef,
  getIncomingStockReportTypeDef,
  addRecentTypeDef,
  getAllRecentProductsTypeDef,
  getNotificationTypeDef,
  addStockTypeDef,
} from './typeDefs';

import {
  getRoles,
  getRoleSelection,
  getAllUsers,
  getUser,
  updateUser,
  getAccessToken,
  addCategory,
  addProduct,
  updateProduct,
  getAllCategories,
  getAllProducts,
  deleteProduct,
  createOrder,
  createRazorpayOrder,
  recordPaymentTransaction,
  verifyRazorpayPayment,
  cancelOrder,
  updateOrder,
  getAllOrders,
  getOrder,
  getSales,
  getSalesReport,
  getTransactions,
  getTransactionsReport,
  getIncomingStock,
  getIncomingStockReport,
  addRecent,
  getAllRecentProducts,
  getNotifications,
  markNotificationRead,
  addStock,
} from './resolvers';

export const typeDefs = mergeTypeDefs([
  enumTypeDef,
  modelTypeDef,
  getRolesTypeDef,
  getAllUsersTypeDef,
  getUserTypeDef,
  updateUserTypeDef,
  getAccessTokenTypeDef,
  addCategoryTypeDef,
  addProductTypeDef,
  getAllCategoriesTypeDef,
  updateProductTypeDef,
  getAllProductsTypeDef,
  deleteProductTypeDef,
  createOrderTypeDefs,
  paymentTypeDef,
  cancelOrderTypeDef,
  updateOrderTypeDef,
  getAllOrdersTypeDef,
  getOrderTypeDef,
  getSalesTypeDef,
  getSalesReportTypeDef,
  getTransactionsTypeDef,
  getTransactionsReportTypeDef,
  getIncomingStockTypeDef,
  getIncomingStockReportTypeDef,
  addRecentTypeDef,
  getAllRecentProductsTypeDef,
  getNotificationTypeDef,
  addStockTypeDef,
]);

export const resolvers = {
  Query: {
    getRoles,
    getRoleSelection,
    getAllUsers,
    getUser,
    getAccessToken,
    getAllCategories,
    getAllProducts,
    getAllOrders,
    getOrder,
    getSales,
    getSalesReport,
    getTransactions,
    getIncomingStock,
    getIncomingStockReport,
    getAllRecentProducts,
    getNotifications,
  },
  Mutation: {
    updateUser,
    addCategory,
    addProduct,
    updateProduct,
    deleteProduct,
    createOrder,
    createRazorpayOrder,
    recordPaymentTransaction,
    verifyRazorpayPayment,
    getTransactionsReport,
    cancelOrder,
    updateOrder,
    addRecent,
    markNotificationRead,
    addStock,
  },
};
